// Import all trigger handlers to register them via side effects
import './card-moved-to'
import './card-moved-from'
import './card-moved-between'
import './card-created'
import './card-archived'
import './card-deleted'
import './card-assignee-set'
import './card-assignee-removed'
import './card-priority-changed'
import './card-tag-added'
import './card-tag-removed'
import './card-due-date-set'
import './due-date-approaching'
import './due-date-passed'
import './card-field-changed'
import './card-stuck-in-column'
