// Top ~300 US cities by population (simplified list for autocomplete)
export const US_CITIES = [
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego",
  "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "San Francisco",
  "Indianapolis", "Seattle", "Denver", "Washington", "Boston", "El Paso", "Nashville", "Detroit",
  "Oklahoma City", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque",
  "Tucson", "Fresno", "Mesa", "Sacramento", "Atlanta", "Kansas City", "Colorado Springs", "Raleigh",
  "Omaha", "Miami", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tulsa", "Tampa",
  "Arlington", "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora", "Honolulu", "Anaheim",
  "Santa Ana", "St. Louis", "Riverside", "Corpus Christi", "Lexington", "Pittsburgh", "Anchorage", "Stockton",
  "Cincinnati", "St. Paul", "Toledo", "Newark", "Greensboro", "Plano", "Henderson", "Lincoln",
  "Buffalo", "Jersey City", "Chula Vista", "Fort Wayne", "Orlando", "St. Petersburg", "Chandler", "Laredo",
  "Norfolk", "Durham", "Madison", "Lubbock", "Winston-Salem", "Garland", "Glendale", "Hialeah",
  "Reno", "Baton Rouge", "Irvine", "Chesapeake", "Irving", "North Las Vegas", "Scottsdale", "Gilbert",
  "San Bernardino", "Boise", "Birmingham", "Rochester", "Richmond", "Spokane", "Des Moines", "Montgomery",
  "Modesto", "Fremont", "Shreveport", "Augusta", "Grand Rapids", "Columbus", "Salt Lake City", "Tallahassee",
  "Huntsville", "Grand Prairie", "Knoxville", "Worcester", "Newport News", "Brownsville", "Santa Clarita",
  "Overland Park", "Providence", "Garden Grove", "Santa Rosa", "Chattanooga", "Oceanside", "Jackson",
  "Fort Lauderdale", "Santa Clara", "Rancho Cucamonga", "Port St. Lucie", "Tempe", "Ontario", "Vancouver",
  "Springfield", "Cape Coral", "Pembroke Pines", "Sioux Falls", "Peoria", "Lancaster", "Elk Grove",
  "Palmdale", "Salinas", "Springfield", "Pomona", "Pasadena", "Fort Collins", "Salem", "Corona",
  "Eugene", "McKinney", "North Charleston", "Rockford", "Joliet", "Torrance", "Paterson", "Kansas City",
  "Savannah", "Hollywood", "Lakewood", "Naperville", "Pasadena", "Hayward", "Orange", "Mesquite",
  "Sunnyvale", "Dayton", "Cary", "Hampton", "Pasadena", "Warren", "Hampton", "McAllen", "Alexandria",
  "Little Rock", "Columbus", "Salt Lake City", "Grand Prairie", "Aurora", "Moreno Valley", "Amarillo",
  "Glendale", "Mobile", "Huntington Beach", "Columbus", "Huntsville", "Port St. Lucie", "Olathe",
  "Fort Wayne", "Sterling Heights", "Laredo", "Sunrise", "Charleston", "Tallahassee", "Waco", "Grand Prairie",
  "Yonkers", "Frisco", "San Marcos", "Glendale", "Newport News", "Round Rock", "Miramar", "Denton",
  "West Valley City", "Wichita Falls", "Green Bay", "Daly City", "Burbank", "Richardson", "Pompano Beach",
  "Broken Arrow", "North Las Vegas", "Westminster", "High Point", "Boulder", "Santa Maria", "El Cajon",
  "Riverside", "Lewisville", "Davenport", "Woodbridge", "Manchester", "Rialto", "Las Cruces", "San Mateo",
  "Rockford", "Rochester", "Richmond", "Murrieta", "Cambridge", "Antioch", "Temecula", "Springfield",
  "Tucson", "Norwalk", "San Angelo", "Bloomington", "Escondido", "Columbia", "Killeen", "Canton",
  "Largo", "Thornton", "Peoria", "Wilmington", "Arvada", "Westminster", "Midland", "Norman",
  "Richmond", "Clearwater", "Odessa", "Miami Gardens", "West Covina", "Bend", "South Bend", "Daly City",
  "Palm Bay", "Everett", "Renton", "Davie", "Edison", "El Monte", "Carmel", "Spokane Valley", "San Leandro",
  "Jurupa Valley", "Berkeley", "Downey", "Rialto", "Las Cruces", "San Marcos", "Spring", "Livonia",
  "Lawton", "Vista", "Woodbridge", "Dearborn", "South Gate", "League City", "San Ramon", "Tyler",
  "Roswell", "Brooklyn Park", "Greenville", "Wilson", "Lake Forest", "Allen", "Las Vegas", "Gresham",
  "Vacaville", "Westminster", "Fairfield", "Evansville", "Port Huron", "Columbus", "Simi Valley",
  "Fayetteville", "Kenosha", "Thousand Oaks", "Lakeland", "Clarksville", "Brandon", "Cedar Rapids",
  "New Haven", "Deltona", "San Bernardino", "St. George", "Rochester", "Hillsboro", "Concord", "Columbus",
  "Columbia", "Kissimmee", "Warren", "Woodbridge", "Norfolk", "Mission Viejo", "Albany", "Portsmouth",
  "Dearborn", "South Gate", "Bloomington", "Trenton", "Carson", "Palm Coast", "Sanford", "Chandler",
  "Fayetteville", "Lee's Summit", "Santa Monica", "Santa Fe", "Boulder", "Athens", "Gary", "Longview",
  "Independence", "Lakewood", "Nashua", "Renton", "Pompano Beach", "West Covina", "Burbank", "Round Rock",
  "Norwich", "Richmond", "Edinburg", "Sanford", "Conway", "Green Bay", "Hampton", "Lancaster", "El Monte",
].sort()
